[package]
name = "maasbree"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
pixels = "*"
nalgebra = "*"
winit_input_helper = "*"
winit = "*"
noise = "*"
